{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.2.0.aar",
          "url": "databinding-runtime-7.2.0.aar",
          "size": 62378,
          "sha512": "6f37164b93a2bee12ee73bc58f878d6b980a7200e74baaf6f15691befd87e6b7c60e3693fb00e81fa519f31b3059c7db43615ca6932f50907f76724a116582e0",
          "sha256": "64e7d0a78591402e42066fe60bb96f258dff77f6a5e88ec8622d7199e8985e4c",
          "sha1": "c88522315158b643e949da3711a964b48c51b9fc",
          "md5": "f788f1efebc67b1fd50b162843512d9b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.2.0.aar",
          "url": "databinding-runtime-7.2.0.aar",
          "size": 62378,
          "sha512": "6f37164b93a2bee12ee73bc58f878d6b980a7200e74baaf6f15691befd87e6b7c60e3693fb00e81fa519f31b3059c7db43615ca6932f50907f76724a116582e0",
          "sha256": "64e7d0a78591402e42066fe60bb96f258dff77f6a5e88ec8622d7199e8985e4c",
          "sha1": "c88522315158b643e949da3711a964b48c51b9fc",
          "md5": "f788f1efebc67b1fd50b162843512d9b"
        }
      ]
    }
  ]
}
